version: '3'

services:

  # Node Red
  nodered:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODERED_VERSION=${NODERED_VERSION:-latest}
    
    image: node-red:${NODERED_VERSION:-latest} #This is a way to force Mosquitto version via env variable, by default latest will be used, check compose file specification to be sure. (https://docs.docker.com/compose/compose-file/#interpolation)
    container_name: nodered
    ports:
      - 1880:1880
    volumes:
      - nodered:/data
    restart: unless-stopped
volumes:
  nodered: